-- CashyCash – ייבוא הקטלוג המלא (341 חנויות בהשראת cashback.co.il)
-- נוצר אוטומטית ע"י scripts/gen-catalog-sql.mjs — אין לערוך ידנית.
-- idempotent: מוסיף רק חנויות שעדיין לא קיימות (לפי שם).

insert into public.stores
  (name, category, base_url, cashback_type, cashback_value, user_share_percent, variable, active)
select v.name, v.category, v.base_url, v.cashback_type, v.cashback_value,
       v.user_share_percent, v.variable, v.active
from (values
  ('המשביר 365', 'קניות כלליות', 'https://365mashbir.co.il', 'percent', 5, 60, false, true),
  ('4chef', 'בית וריהוט', 'https://4chef.co.il', 'percent', 4, 60, false, true),
  ('AbeBooks', 'ספרים', 'https://abebooks.com', 'percent', 4, 60, false, true),
  ('Accessorize', 'אופנה', 'https://accessorize.com', 'percent', 6, 60, false, true),
  ('ACE', 'בית וריהוט', 'https://ace.co.il', 'percent', 4, 60, false, true),
  ('עדה לזורגן', 'אופנה', 'https://adahlazorgan.co.il', 'percent', 6, 60, false, true),
  ('Adidas', 'ספורט', 'https://adidas.co.il', 'percent', 5, 60, false, true),
  ('Adorama', 'אלקטרוניקה', 'https://adorama.com', 'percent', 3, 60, false, true),
  ('AFI Hotels', 'טיסות ומלונות', 'https://afi-hotels.com', 'percent', 4, 60, false, true),
  ('Agoda', 'טיסות ומלונות', 'https://agoda.com', 'percent', 4, 60, false, true),
  ('AHAVA', 'יופי וטיפוח', 'https://ahava.com', 'percent', 6, 60, false, true),
  ('אהבה קטנה', 'ילדים ותינוקות', 'https://ahavaktana.co.il', 'percent', 5, 60, false, true),
  ('Airalo', 'שירותים דיגיטליים', 'https://airalo.com', 'percent', 8, 60, false, true),
  ('AirHelp', 'טיסות ומלונות', 'https://airhelp.com', 'percent', 4, 60, false, true),
  ('Air India', 'טיסות ומלונות', 'https://airindia.com', 'percent', 4, 60, false, true),
  ('Albume', 'שירותים דיגיטליים', 'https://albume.co.il', 'percent', 8, 60, false, true),
  ('Alibaba', 'קניות כלליות', 'https://alibaba.com', 'percent', 5, 60, false, true),
  ('AliExpress', 'קניות כלליות', 'https://aliexpress.com', 'percent', 5, 60, false, true),
  ('All In Pro', 'אלקטרוניקה', 'https://allinpro.co.il', 'percent', 3, 60, false, true),
  ('Allur', 'אופנה', 'https://allur.co.il', 'percent', 6, 60, false, true),
  ('אלם', 'אופנה', 'https://alm.co.il', 'percent', 6, 60, false, true),
  ('אלוף הספורט', 'ספורט', 'https://alufsport.co.il', 'percent', 5, 60, false, true),
  ('Amaro', 'אופנה', 'https://amaro.com', 'percent', 6, 60, false, true),
  ('Amazon', 'קניות כלליות', 'https://amazon.com', 'percent', 5, 60, false, true),
  ('Amika', 'יופי וטיפוח', 'https://loveamika.com', 'percent', 6, 60, false, true),
  ('ארד טקסטיל', 'בית וריהוט', 'https://aradtextile.co.il', 'percent', 4, 60, false, true),
  ('Argento', 'אופנה', 'https://argento.com', 'percent', 6, 60, false, true),
  ('ASOS', 'אופנה', 'https://asos.com', 'percent', 6, 60, false, true),
  ('Auto Depot', 'קניות כלליות', 'https://autodepot.co.il', 'percent', 5, 60, false, true),
  ('Avast', 'שירותים דיגיטליים', 'https://avast.com', 'percent', 8, 60, false, true),
  ('AVG', 'שירותים דיגיטליים', 'https://avg.com', 'percent', 8, 60, false, true),
  ('BadRhino', 'אופנה', 'https://badrhino.com', 'percent', 6, 60, false, true),
  ('Banggood', 'אלקטרוניקה', 'https://banggood.com', 'percent', 3, 60, false, true),
  ('Bath & Body Works', 'יופי וטיפוח', 'https://bathandbodyworks.com', 'percent', 6, 60, false, true),
  ('Beautiful J', 'אופנה', 'https://beautifulj.co.il', 'percent', 6, 60, false, true),
  ('Belle Lingerie', 'אופנה', 'https://bellelingerie.co.uk', 'percent', 6, 60, false, true),
  ('Best Buy', 'אלקטרוניקה', 'https://bestbuy.com', 'percent', 3, 60, false, true),
  ('Best Western', 'טיסות ומלונות', 'https://bestwestern.com', 'percent', 4, 60, false, true),
  ('Best Western UK', 'טיסות ומלונות', 'https://bestwestern.co.uk', 'percent', 4, 60, false, true),
  ('Betili', 'אופנה', 'https://betili.co.il', 'percent', 6, 60, false, true),
  ('Bhuka', 'מזון ומשלוחים', 'https://bhuka.co.il', 'percent', 4, 60, false, true),
  ('Bissell', 'בית וריהוט', 'https://bissell.com', 'percent', 4, 60, false, true),
  ('Bitter', 'אופנה', 'https://bitter.co.il', 'percent', 6, 60, false, true),
  ('Black Halo', 'אופנה', 'https://blackhalo.com', 'percent', 6, 60, false, true),
  ('Bloomingdale''s', 'אופנה', 'https://bloomingdales.com', 'percent', 6, 60, false, true),
  ('Booking.com', 'טיסות ומלונות', 'https://booking.com', 'percent', 4, 60, false, true),
  ('Booknet', 'ספרים', 'https://booknet.co.il', 'percent', 4, 60, false, true),
  ('Budget Pet World', 'חיות מחמד', 'https://budgetpetworld.com', 'percent', 6, 60, false, true),
  ('Carter''s OshKosh', 'ילדים ותינוקות', 'https://carters.com', 'percent', 5, 60, false, true),
  ('Cathay Pacific', 'טיסות ומלונות', 'https://cathaypacific.com', 'percent', 4, 60, false, true),
  ('CheapTickets', 'טיסות ומלונות', 'https://cheaptickets.com', 'percent', 4, 60, false, true),
  ('Chegg', 'ספרים', 'https://chegg.com', 'percent', 4, 60, false, true),
  ('Chic Me', 'אופנה', 'https://chicme.com', 'percent', 6, 60, false, true),
  ('Cinema City', 'פנאי ובידור', 'https://cinema-city.co.il', 'percent', 4, 60, false, true),
  ('citizenM', 'טיסות ומלונות', 'https://citizenm.com', 'percent', 4, 60, false, true),
  ('City Travel', 'טיסות ומלונות', 'https://city-travel.co.il', 'percent', 4, 60, false, true),
  ('Claire''s', 'אופנה', 'https://claires.com', 'percent', 6, 60, false, true),
  ('כלל ביטוח', 'פיננסים וביטוח', 'https://clal.co.il', 'percent', 3, 60, false, true),
  ('Clever', 'שירותים דיגיטליים', 'https://clever.co.il', 'percent', 8, 60, false, true),
  ('Cole Haan', 'אופנה', 'https://colehaan.com', 'percent', 6, 60, false, true),
  ('Cook & Bake', 'בית וריהוט', 'https://cookandbake.co.il', 'percent', 4, 60, false, true),
  ('Cotosen', 'אופנה', 'https://cotosen.com', 'percent', 6, 60, false, true),
  ('Cult Beauty', 'יופי וטיפוח', 'https://cultbeauty.com', 'percent', 6, 60, false, true),
  ('Cupshe', 'אופנה', 'https://cupshe.com', 'percent', 6, 60, false, true),
  ('Currys PartMaster', 'אלקטרוניקה', 'https://partmaster.co.uk', 'percent', 3, 60, false, true),
  ('CWC', 'קניות כלליות', 'https://cwc.co.il', 'percent', 5, 60, false, true),
  ('CyberGhost VPN', 'שירותים דיגיטליים', 'https://cyberghostvpn.com', 'percent', 8, 60, false, true),
  ('Deasy', 'אופנה', 'https://deasy.co.il', 'percent', 6, 60, false, true),
  ('Delta', 'אופנה', 'https://delta.co.il', 'percent', 6, 60, false, true),
  ('DHgate', 'קניות כלליות', 'https://dhgate.com', 'percent', 5, 60, false, true),
  ('Dio Express', 'קניות כלליות', 'https://dioexpress.co.il', 'percent', 5, 60, false, true),
  ('Discover Cars', 'טיסות ומלונות', 'https://discovercars.com', 'percent', 4, 60, false, true),
  ('Disney Store', 'ילדים ותינוקות', 'https://shopdisney.com', 'percent', 5, 60, false, true),
  ('דוקטור גב', 'בית וריהוט', 'https://dr-gav.co.il', 'percent', 4, 60, false, true),
  ('Dream Machine', 'אלקטרוניקה', 'https://dreammachine.co.il', 'percent', 3, 60, false, true),
  ('Dyn Store', 'קניות כלליות', 'https://dynstore.co.il', 'percent', 5, 60, false, true),
  ('EatWith', 'פנאי ובידור', 'https://eatwith.com', 'percent', 4, 60, false, true),
  ('eBay', 'קניות כלליות', 'https://ebay.com', 'percent', 5, 60, false, true),
  ('EconomyBookings', 'טיסות ומלונות', 'https://economybookings.com', 'percent', 4, 60, false, true),
  ('Ecosall', 'בית וריהוט', 'https://ecosall.com', 'percent', 4, 60, false, true),
  ('eDreams', 'טיסות ומלונות', 'https://edreams.com', 'percent', 4, 60, false, true),
  ('Electrical Europe', 'אלקטרוניקה', 'https://electricaleurope.com', 'percent', 3, 60, false, true),
  ('Ellesse', 'ספורט', 'https://ellesse.com', 'percent', 5, 60, false, true),
  ('English Ways', 'ספרים', 'https://englishways.co.il', 'percent', 4, 60, false, true),
  ('Envato', 'שירותים דיגיטליים', 'https://envato.com', 'percent', 8, 60, false, true),
  ('אשת טורס', 'טיסות ומלונות', 'https://eshettours.co.il', 'percent', 4, 60, false, true),
  ('Eshli', 'אופנה', 'https://eshli.co.il', 'percent', 6, 60, false, true),
  ('eSIM Fly', 'שירותים דיגיטליים', 'https://esimfly.net', 'percent', 8, 60, false, true),
  ('eSIMo', 'שירותים דיגיטליים', 'https://esimo.co', 'percent', 8, 60, false, true),
  ('Ethiopian Airlines', 'טיסות ומלונות', 'https://ethiopianairlines.com', 'percent', 4, 60, false, true),
  ('Etihad Airways', 'טיסות ומלונות', 'https://etihad.com', 'percent', 4, 60, false, true),
  ('Europcar', 'טיסות ומלונות', 'https://europcar.com', 'percent', 4, 60, false, true),
  ('Euro Sport', 'ספורט', 'https://euro-sport.co.il', 'percent', 5, 60, false, true),
  ('Eurowings', 'טיסות ומלונות', 'https://eurowings.com', 'percent', 4, 60, false, true),
  ('e-vrit', 'ספרים', 'https://e-vrit.co.il', 'percent', 4, 60, false, true),
  ('Expedia', 'טיסות ומלונות', 'https://expedia.com', 'percent', 4, 60, false, true),
  ('Eyeconic', 'יופי וטיפוח', 'https://eyeconic.com', 'percent', 6, 60, false, true),
  ('Farfetch', 'אופנה', 'https://farfetch.com', 'percent', 6, 60, false, true),
  ('פתאל', 'טיסות ומלונות', 'https://fattal.co.il', 'percent', 4, 60, false, true),
  ('Fenix Travel Insurance', 'טיסות ומלונות', 'https://fenixinsurance.co.il', 'percent', 4, 60, false, true),
  ('FIB Trade', 'קניות כלליות', 'https://fib-trade.co.il', 'percent', 5, 60, false, true),
  ('First Class Watches', 'אופנה', 'https://firstclasswatches.com', 'percent', 6, 60, false, true),
  ('Fiverr', 'שירותים דיגיטליים', 'https://fiverr.com', 'percent', 8, 60, false, true),
  ('Fix', 'אופנה', 'https://fix.co.il', 'percent', 6, 60, false, true),
  ('Flight Network', 'טיסות ומלונות', 'https://flightnetwork.com', 'percent', 4, 60, false, true),
  ('Flower Net', 'מזון ומשלוחים', 'https://flowernet.co.il', 'percent', 4, 60, false, true),
  ('FOX', 'אופנה', 'https://fox.co.il', 'percent', 6, 60, false, true),
  ('FOX Home', 'בית וריהוט', 'https://foxhome.co.il', 'percent', 4, 60, false, true),
  ('FragranceX', 'יופי וטיפוח', 'https://fragrancex.com', 'percent', 6, 60, false, true),
  ('Fun', 'פנאי ובידור', 'https://fun.co.il', 'percent', 4, 60, false, true),
  ('G2A', 'שירותים דיגיטליים', 'https://g2a.com', 'percent', 8, 60, false, true),
  ('Gade', 'אופנה', 'https://gade.co.il', 'percent', 6, 60, false, true),
  ('Gamivo', 'שירותים דיגיטליים', 'https://gamivo.com', 'percent', 8, 60, false, true),
  ('Geekbuying', 'אלקטרוניקה', 'https://geekbuying.com', 'percent', 3, 60, false, true),
  ('GetYourGuide', 'פנאי ובידור', 'https://getyourguide.com', 'percent', 4, 60, false, true),
  ('GlassesLit', 'יופי וטיפוח', 'https://glasseslit.com', 'percent', 6, 60, false, true),
  ('Go Car Insurance', 'פיננסים וביטוח', 'https://go-insurance.co.il', 'percent', 3, 60, false, true),
  ('Go City', 'פנאי ובידור', 'https://gocity.com', 'percent', 4, 60, false, true),
  ('GoDaddy', 'שירותים דיגיטליים', 'https://godaddy.com', 'percent', 8, 60, false, true),
  ('GOLF', 'אופנה', 'https://golf-fashion.co.il', 'percent', 6, 60, false, true),
  ('GOLF&CO', 'בית וריהוט', 'https://golfand.co.il', 'percent', 4, 60, false, true),
  ('GOLF KIDS', 'ילדים ותינוקות', 'https://golf-fashion.co.il', 'percent', 5, 60, false, true),
  ('Gotogate', 'טיסות ומלונות', 'https://gotogate.com', 'percent', 4, 60, false, true),
  ('Green Man Gaming', 'שירותים דיגיטליים', 'https://greenmangaming.com', 'percent', 8, 60, false, true),
  ('Gulliver', 'טיסות ומלונות', 'https://gulliver.co.il', 'percent', 4, 60, false, true),
  ('Halloween Costumes', 'פנאי ובידור', 'https://halloweencostumes.com', 'percent', 4, 60, false, true),
  ('Hanes', 'אופנה', 'https://hanes.com', 'percent', 6, 60, false, true),
  ('הראל ביטוח', 'פיננסים וביטוח', 'https://harel-group.co.il', 'percent', 3, 60, false, true),
  ('יקב היוצר', 'מזון ומשלוחים', 'https://hayotzer-winery.co.il', 'percent', 4, 60, false, true),
  ('Herbs-Pro', 'בריאות וטבע', 'https://herbspro.com', 'percent', 6, 60, false, true),
  ('H.O', 'אופנה', 'https://h-o.co.il', 'percent', 6, 60, false, true),
  ('HomEat', 'מזון ומשלוחים', 'https://homeat.co.il', 'percent', 4, 60, false, true),
  ('Home Center', 'בית וריהוט', 'https://homecenter.co.il', 'percent', 4, 60, false, true),
  ('HomeSet', 'בית וריהוט', 'https://homeset.co.il', 'percent', 4, 60, false, true),
  ('Hoodies', 'אופנה', 'https://hoodies.co.il', 'percent', 6, 60, false, true),
  ('Hostinger', 'שירותים דיגיטליים', 'https://hostinger.com', 'percent', 8, 60, false, true),
  ('Hotels.com', 'טיסות ומלונות', 'https://hotels.com', 'percent', 4, 60, false, true),
  ('House of Marley', 'אלקטרוניקה', 'https://thehouseofmarley.com', 'percent', 3, 60, false, true),
  ('Hulyo', 'אופנה', 'https://hulyo.co.il', 'percent', 6, 60, false, true),
  ('Iberostar', 'טיסות ומלונות', 'https://iberostar.com', 'percent', 4, 60, false, true),
  ('iCount', 'שירותים דיגיטליים', 'https://icount.co.il', 'percent', 8, 60, false, true),
  ('iHerb', 'בריאות וטבע', 'https://iherb.com', 'percent', 6, 60, false, true),
  ('IHG Hotels', 'טיסות ומלונות', 'https://ihg.com', 'percent', 4, 60, false, true),
  ('Intima', 'אופנה', 'https://intima.co.il', 'percent', 6, 60, false, true),
  ('Intimina', 'בריאות וטבע', 'https://intimina.com', 'percent', 6, 60, false, true),
  ('i-Optic', 'יופי וטיפוח', 'https://i-optic.co.il', 'percent', 6, 60, false, true),
  ('Israel Gifts', 'פנאי ובידור', 'https://israelgifts.com', 'percent', 4, 60, false, true),
  ('Isrotel', 'טיסות ומלונות', 'https://isrotel.co.il', 'percent', 4, 60, false, true),
  ('italki', 'ספרים', 'https://italki.com', 'percent', 4, 60, false, true),
  ('Ivory', 'אלקטרוניקה', 'https://ivory.co.il', 'percent', 3, 60, false, true),
  ('IWOOT', 'פנאי ובידור', 'https://iwantoneofthose.com', 'percent', 4, 60, false, true),
  ('Jacobi', 'בית וריהוט', 'https://jacobi.co.il', 'percent', 4, 60, false, true),
  ('JFN', 'קניות כלליות', 'https://jfn.co.il', 'percent', 5, 60, false, true),
  ('Joom', 'קניות כלליות', 'https://joom.com', 'percent', 5, 60, false, true),
  ('Kaitz', 'אופנה', 'https://kaitz.co.il', 'percent', 6, 60, false, true),
  ('Kamedis', 'בריאות וטבע', 'https://kamedis.com', 'percent', 6, 60, false, true),
  ('Kangaroo Sleep', 'בית וריהוט', 'https://kangaroosleep.co.il', 'percent', 4, 60, false, true),
  ('Kaniti', 'קניות כלליות', 'https://kaniti.online', 'percent', 5, 60, false, true),
  ('Keter', 'בית וריהוט', 'https://keter.com', 'percent', 4, 60, false, true),
  ('Kiko Milano', 'יופי וטיפוח', 'https://kikocosmetics.com', 'percent', 6, 60, false, true),
  ('Kinguin', 'שירותים דיגיטליים', 'https://kinguin.net', 'percent', 8, 60, false, true),
  ('כיתן', 'בית וריהוט', 'https://kitan.co.il', 'percent', 4, 60, false, true),
  ('Kiwi.com', 'טיסות ומלונות', 'https://kiwi.com', 'percent', 4, 60, false, true),
  ('Klook', 'פנאי ובידור', 'https://klook.com', 'percent', 4, 60, false, true),
  ('קרביץ', 'קניות כלליות', 'https://kravitz.co.il', 'percent', 5, 60, false, true),
  ('KSP', 'אלקטרוניקה', 'https://ksp.co.il', 'percent', 3, 60, false, true),
  ('קופת בראבו', 'קניות כלליות', 'https://kupatbravo.co.il', 'percent', 5, 60, false, true),
  ('Labass', 'אופנה', 'https://labass.co.il', 'percent', 6, 60, false, true),
  ('lastminute.com', 'טיסות ומלונות', 'https://lastminute.com', 'percent', 4, 60, false, true),
  ('Last Price', 'קניות כלליות', 'https://lastprice.co.il', 'percent', 5, 60, false, true),
  ('Lavido', 'יופי וטיפוח', 'https://lavido.com', 'percent', 6, 60, false, true),
  ('Lee Jeans', 'אופנה', 'https://lee.com', 'percent', 6, 60, false, true),
  ('Leo Jewelry', 'אופנה', 'https://leo-jewelry.co.il', 'percent', 6, 60, false, true),
  ('Liberty London', 'אופנה', 'https://libertylondon.com', 'percent', 6, 60, false, true),
  ('Libra', 'אופנה', 'https://libra.co.il', 'percent', 6, 60, false, true),
  ('LightInTheBox', 'קניות כלליות', 'https://lightinthebox.com', 'percent', 5, 60, false, true),
  ('Lion King', 'פנאי ובידור', 'https://lionking.co.il', 'percent', 4, 60, false, true),
  ('Lior', 'אופנה', 'https://lior.co.il', 'percent', 6, 60, false, true),
  ('Living DNA', 'בריאות וטבע', 'https://livingdna.com', 'percent', 6, 60, false, true),
  ('Loaded', 'אופנה', 'https://loaded.co.il', 'percent', 6, 60, false, true),
  ('Lookfantastic', 'יופי וטיפוח', 'https://lookfantastic.com', 'percent', 6, 60, false, true),
  ('LOT Polish Airlines', 'טיסות ומלונות', 'https://lot.com', 'percent', 4, 60, false, true),
  ('Lucky2Go', 'טיסות ומלונות', 'https://lucky2go.com', 'percent', 4, 60, false, true),
  ('Macy''s', 'אופנה', 'https://macys.com', 'percent', 6, 60, false, true),
  ('Mania Jeans', 'אופנה', 'https://maniajeans.co.il', 'percent', 6, 60, false, true),
  ('MDS Pharm', 'בריאות וטבע', 'https://mdspharm.co.il', 'percent', 6, 60, false, true),
  ('Me-Book', 'שירותים דיגיטליים', 'https://me-book.co.il', 'percent', 8, 60, false, true),
  ('מנורה מבטחים', 'פיננסים וביטוח', 'https://menoramivt.co.il', 'percent', 3, 60, false, true),
  ('מסיבה לנד', 'פנאי ובידור', 'https://mesibalend.co.il', 'percent', 4, 60, false, true),
  ('מגדל ביטוח', 'פיננסים וביטוח', 'https://migdal.co.il', 'percent', 3, 60, false, true),
  ('מגדל דירה אונליין', 'פיננסים וביטוח', 'https://migdal.co.il', 'percent', 3, 60, false, true),
  ('מגדל רכב אונליין', 'פיננסים וביטוח', 'https://migdal.co.il', 'percent', 3, 60, false, true),
  ('מגדל משכנתא', 'פיננסים וביטוח', 'https://migdal.co.il', 'percent', 3, 60, false, true),
  ('Milega', 'אופנה', 'https://milega.co.il', 'percent', 6, 60, false, true),
  ('Millennium Hotels', 'טיסות ומלונות', 'https://millenniumhotels.com', 'percent', 4, 60, false, true),
  ('Minor Hotels', 'טיסות ומלונות', 'https://minorhotels.com', 'percent', 4, 60, false, true),
  ('מירי לב', 'אופנה', 'https://mirilev.co.il', 'percent', 6, 60, false, true),
  ('Mishloha', 'מזון ומשלוחים', 'https://mishloha.co.il', 'percent', 4, 60, false, true),
  ('Modelones', 'יופי וטיפוח', 'https://modelones.com', 'percent', 6, 60, false, true),
  ('Modibodi', 'אופנה', 'https://modibodi.com', 'percent', 6, 60, false, true),
  ('Modlily', 'אופנה', 'https://modlily.com', 'percent', 6, 60, false, true),
  ('Mommy Care', 'ילדים ותינוקות', 'https://mommycare.co.il', 'percent', 5, 60, false, true),
  ('monday.com', 'שירותים דיגיטליים', 'https://monday.com', 'percent', 8, 60, false, true),
  ('Marks & Spencer', 'אופנה', 'https://marksandspencer.com', 'percent', 6, 60, false, true),
  ('Multistore', 'קניות כלליות', 'https://multistore.co.il', 'percent', 5, 60, false, true),
  ('My 1st Years', 'ילדים ותינוקות', 'https://my1styears.com', 'percent', 5, 60, false, true),
  ('MyHeritage', 'שירותים דיגיטליים', 'https://myheritage.com', 'percent', 8, 60, false, true),
  ('נעמן', 'בית וריהוט', 'https://naaman.co.il', 'percent', 4, 60, false, true),
  ('Namecheap', 'שירותים דיגיטליים', 'https://namecheap.com', 'percent', 8, 60, false, true),
  ('Napo', 'חיות מחמד', 'https://napo.pet', 'percent', 6, 60, false, true),
  ('Naturalizer', 'אופנה', 'https://naturalizer.com', 'percent', 6, 60, false, true),
  ('Nautica', 'אופנה', 'https://nautica.com', 'percent', 6, 60, false, true),
  ('NBA Store', 'ספורט', 'https://nba.com', 'percent', 5, 60, false, true),
  ('Neal''s Yard', 'יופי וטיפוח', 'https://nealsyardremedies.com', 'percent', 6, 60, false, true),
  ('NET-A-PORTER', 'אופנה', 'https://net-a-porter.com', 'percent', 6, 60, false, true),
  ('נטו אנד נטו', 'קניות כלליות', 'https://netoneto.co.il', 'percent', 5, 60, false, true),
  ('Newegg', 'אלקטרוניקה', 'https://newegg.com', 'percent', 3, 60, false, true),
  ('New Era', 'אופנה', 'https://neweracap.com', 'percent', 6, 60, false, true),
  ('New Feet', 'אופנה', 'https://newfeet.co.il', 'percent', 6, 60, false, true),
  ('NHW', 'בריאות וטבע', 'https://nhw.co.il', 'percent', 6, 60, false, true),
  ('Noa Kirel Store', 'אופנה', 'https://noakirel.co.il', 'percent', 6, 60, false, true),
  ('Noizz', 'אלקטרוניקה', 'https://noizz.co.il', 'percent', 3, 60, false, true),
  ('NordVPN', 'שירותים דיגיטליים', 'https://nordvpn.com', 'percent', 8, 60, false, true),
  ('Novakid', 'ספרים', 'https://novakid.com', 'percent', 4, 60, false, true),
  ('Ofran', 'אופנה', 'https://ofran.co.il', 'percent', 6, 60, false, true),
  ('Olier Paris', 'יופי וטיפוח', 'https://oliereparis.com', 'percent', 6, 60, false, true),
  ('OneTravel', 'טיסות ומלונות', 'https://onetravel.com', 'percent', 4, 60, false, true),
  ('Opticana', 'יופי וטיפוח', 'https://opticana.co.il', 'percent', 6, 60, false, true),
  ('Orbitz', 'טיסות ומלונות', 'https://orbitz.com', 'percent', 4, 60, false, true),
  ('Otticanet', 'יופי וטיפוח', 'https://otticanet.com', 'percent', 6, 60, false, true),
  ('Owl Market', 'קניות כלליות', 'https://owlmarket.co.il', 'percent', 5, 60, false, true),
  ('PandaHall', 'אופנה', 'https://pandahall.com', 'percent', 6, 60, false, true),
  ('Panda', 'קניות כלליות', 'https://pandazzz.co.il', 'percent', 5, 60, false, true),
  ('Paneco', 'מזון ומשלוחים', 'https://paneco.co.il', 'percent', 4, 60, false, true),
  ('Panta Rei', 'אופנה', 'https://pantarei.co.il', 'percent', 6, 60, false, true),
  ('Partner', 'שירותים דיגיטליים', 'https://partner.co.il', 'percent', 8, 60, false, true),
  ('PassportCard', 'טיסות ומלונות', 'https://passportcard.co.il', 'percent', 4, 60, false, true),
  ('PatPat', 'ילדים ותינוקות', 'https://patpat.com', 'percent', 5, 60, false, true),
  ('Payoneer', 'פיננסים וביטוח', 'https://payoneer.com', 'percent', 3, 60, false, true),
  ('Perfume', 'יופי וטיפוח', 'https://perfume.co.il', 'percent', 6, 60, false, true),
  ('Pet Care Club', 'חיות מחמד', 'https://petcareclub.com', 'percent', 6, 60, false, true),
  ('Pet Care Supplies', 'חיות מחמד', 'https://petcaresupplies.com', 'percent', 6, 60, false, true),
  ('Pharmacy2U', 'בריאות וטבע', 'https://pharmacy2u.co.uk', 'percent', 6, 60, false, true),
  ('Plant It', 'בית וריהוט', 'https://plantit.co.il', 'percent', 4, 60, false, true),
  ('Platin Express', 'קניות כלליות', 'https://platinexpress.co.il', 'percent', 5, 60, false, true),
  ('Polgat', 'אופנה', 'https://polgat.co.il', 'percent', 6, 60, false, true),
  ('PrettyLittleThing', 'אופנה', 'https://prettylittlething.com', 'percent', 6, 60, false, true),
  ('Priceline', 'טיסות ומלונות', 'https://priceline.com', 'percent', 4, 60, false, true),
  ('Public Desire', 'אופנה', 'https://publicdesire.com', 'percent', 6, 60, false, true),
  ('PureVPN', 'שירותים דיגיטליים', 'https://purevpn.com', 'percent', 8, 60, false, true),
  ('Radisson Hotels', 'טיסות ומלונות', 'https://radissonhotels.com', 'percent', 4, 60, false, true),
  ('Rahiti', 'בית וריהוט', 'https://rahiti.co.il', 'percent', 4, 60, false, true),
  ('Razili', 'אופנה', 'https://razili.co.il', 'percent', 6, 60, false, true),
  ('Redefine Hair', 'יופי וטיפוח', 'https://redefine-hair.co.il', 'percent', 6, 60, false, true),
  ('RedMagic', 'אלקטרוניקה', 'https://redmagic.gg', 'percent', 3, 60, false, true),
  ('RentCarLA', 'טיסות ומלונות', 'https://rentcarla.com', 'percent', 4, 60, false, true),
  ('Renuar', 'אופנה', 'https://renuar.co.il', 'percent', 6, 60, false, true),
  ('Replay', 'אופנה', 'https://replay.it', 'percent', 6, 60, false, true),
  ('Reserved', 'אופנה', 'https://reserved.com', 'percent', 6, 60, false, true),
  ('R Gallery', 'בית וריהוט', 'https://rgallery.co.il', 'percent', 4, 60, false, true),
  ('Rosewe', 'אופנה', 'https://rosewe.com', 'percent', 6, 60, false, true),
  ('Rozenfeld', 'בית וריהוט', 'https://rozenfeld.co.il', 'percent', 4, 60, false, true),
  ('Sabon', 'יופי וטיפוח', 'https://sabon.co.il', 'percent', 6, 60, false, true),
  ('Savile Row Company', 'אופנה', 'https://savilerowco.com', 'percent', 6, 60, false, true),
  ('Sephora', 'יופי וטיפוח', 'https://sephora.com', 'percent', 6, 60, false, true),
  ('Shein', 'אופנה', 'https://shein.com', 'percent', 6, 60, false, true),
  ('שילב', 'ילדים ותינוקות', 'https://shilav.co.il', 'percent', 5, 60, false, true),
  ('Shoes Online', 'אופנה', 'https://shoesonline.co.il', 'percent', 6, 60, false, true),
  ('שמרת הזורע', 'בית וריהוט', 'https://shomrat.co.il', 'percent', 4, 60, false, true),
  ('Shopbop', 'אופנה', 'https://shopbop.com', 'percent', 6, 60, false, true),
  ('Shutterstock', 'שירותים דיגיטליים', 'https://shutterstock.com', 'percent', 8, 60, false, true),
  ('Sibel Food', 'מזון ומשלוחים', 'https://sibelfood.co.il', 'percent', 4, 60, false, true),
  ('Simplii Good', 'מזון ומשלוחים', 'https://simpliigood.com', 'percent', 4, 60, false, true),
  ('Size', 'אופנה', 'https://size.co.uk', 'percent', 6, 60, false, true),
  ('SmartBuyGlasses', 'יופי וטיפוח', 'https://smartbuyglasses.com', 'percent', 6, 60, false, true),
  ('SockShop', 'אופנה', 'https://sockshop.co.uk', 'percent', 6, 60, false, true),
  ('Soho', 'בית וריהוט', 'https://soho.co.il', 'percent', 4, 60, false, true),
  ('Soltam', 'בית וריהוט', 'https://soltam.co.il', 'percent', 4, 60, false, true),
  ('Sports Events 365', 'פנאי ובידור', 'https://sportsevents365.com', 'percent', 4, 60, false, true),
  ('Start Home', 'בית וריהוט', 'https://starthome.co.il', 'percent', 4, 60, false, true),
  ('Steimatzky', 'ספרים', 'https://steimatzky.co.il', 'percent', 4, 60, false, true),
  ('Steve Madden', 'אופנה', 'https://stevemadden.com', 'percent', 6, 60, false, true),
  ('StockX', 'אופנה', 'https://stockx.com', 'percent', 6, 60, false, true),
  ('StrawberryNET', 'יופי וטיפוח', 'https://strawberrynet.com', 'percent', 6, 60, false, true),
  ('Strongful', 'ספורט', 'https://strongful.co.il', 'percent', 5, 60, false, true),
  ('StubHub', 'פנאי ובידור', 'https://stubhub.com', 'percent', 4, 60, false, true),
  ('StyleWe', 'אופנה', 'https://stylewe.com', 'percent', 6, 60, false, true),
  ('SunSky', 'אלקטרוניקה', 'https://sunsky-online.com', 'percent', 3, 60, false, true),
  ('Superdry', 'אופנה', 'https://superdry.com', 'percent', 6, 60, false, true),
  ('Super-Pharm', 'יופי וטיפוח', 'https://super-pharm.co.il', 'percent', 6, 60, false, true),
  ('Tami4', 'בית וריהוט', 'https://tami4.co.il', 'percent', 4, 60, false, true),
  ('Temu', 'קניות כלליות', 'https://temu.com', 'percent', 5, 60, false, true),
  ('Terminal X', 'אופנה', 'https://terminalx.com', 'percent', 6, 60, false, true),
  ('TFNC London', 'אופנה', 'https://tfnclondon.com', 'percent', 6, 60, false, true),
  ('The Luxury Closet', 'אופנה', 'https://theluxurycloset.com', 'percent', 6, 60, false, true),
  ('Tiber', 'אופנה', 'https://tiber.co.il', 'percent', 6, 60, false, true),
  ('Ticketmaster', 'פנאי ובידור', 'https://ticketmaster.com', 'percent', 4, 60, false, true),
  ('TicketNetwork', 'פנאי ובידור', 'https://ticketnetwork.com', 'percent', 4, 60, false, true),
  ('Timberland', 'אופנה', 'https://timberland.com', 'percent', 6, 60, false, true),
  ('Tiqets', 'פנאי ובידור', 'https://tiqets.com', 'percent', 4, 60, false, true),
  ('Tollman''s', 'קניות כלליות', 'https://tollmansdot.co.il', 'percent', 5, 60, false, true),
  ('TopCommerce', 'קניות כלליות', 'https://topcommerce.co.il', 'percent', 5, 60, false, true),
  ('Touch Therapy', 'יופי וטיפוח', 'https://touchtherapy.co.il', 'percent', 6, 60, false, true),
  ('Toys R Us', 'ילדים ותינוקות', 'https://toysrus.co.il', 'percent', 5, 60, false, true),
  ('Traklin', 'אלקטרוניקה', 'https://traklin.co.il', 'percent', 3, 60, false, true),
  ('Travelocity', 'טיסות ומלונות', 'https://travelocity.com', 'percent', 4, 60, false, true),
  ('Trip.com', 'טיסות ומלונות', 'https://trip.com', 'percent', 4, 60, false, true),
  ('Trip Guaranty', 'טיסות ומלונות', 'https://tripguaranty.co.il', 'percent', 4, 60, false, true),
  ('True Story', 'אופנה', 'https://truestory.co.il', 'percent', 6, 60, false, true),
  ('Tulip Winery', 'מזון ומשלוחים', 'https://tulip-winery.co.il', 'percent', 4, 60, false, true),
  ('TwentyFourSeven', 'אופנה', 'https://24-7.co.il', 'percent', 6, 60, false, true),
  ('Twinings Teashop', 'מזון ומשלוחים', 'https://twinings.co.uk', 'percent', 4, 60, false, true),
  ('Udemy', 'ספרים', 'https://udemy.com', 'percent', 4, 60, false, true),
  ('Ulike', 'יופי וטיפוח', 'https://ulike.com', 'percent', 6, 60, false, true),
  ('Unineed', 'יופי וטיפוח', 'https://unineed.com', 'percent', 6, 60, false, true),
  ('Urban', 'אופנה', 'https://urban.co.il', 'percent', 6, 60, false, true),
  ('Urbanica', 'אופנה', 'https://urbanica.co.il', 'percent', 6, 60, false, true),
  ('Vardinon', 'בית וריהוט', 'https://vardinon.co.il', 'percent', 4, 60, false, true),
  ('VeePN', 'שירותים דיגיטליים', 'https://veepn.com', 'percent', 8, 60, false, true),
  ('viagogo', 'פנאי ובידור', 'https://viagogo.com', 'percent', 4, 60, false, true),
  ('Viator', 'פנאי ובידור', 'https://viator.com', 'percent', 4, 60, false, true),
  ('Victoria''s Secret', 'אופנה', 'https://victoriassecret.com', 'percent', 6, 60, false, true),
  ('Vision Direct', 'יופי וטיפוח', 'https://visiondirect.co.uk', 'percent', 6, 60, false, true),
  ('VIVAIA', 'אופנה', 'https://vivaia.com', 'percent', 6, 60, false, true),
  ('Voye Global', 'שירותים דיגיטליים', 'https://voyeglobal.com', 'percent', 8, 60, false, true),
  ('Vrbo', 'טיסות ומלונות', 'https://vrbo.com', 'percent', 4, 60, false, true),
  ('Wal-G', 'קניות כלליות', 'https://wal-g.co.il', 'percent', 5, 60, false, true),
  ('Walla Tours', 'טיסות ומלונות', 'https://tours.walla.co.il', 'percent', 4, 60, false, true),
  ('Walmart', 'קניות כלליות', 'https://walmart.com', 'percent', 5, 60, false, true),
  ('WeShoes', 'אופנה', 'https://weshoes.co.il', 'percent', 6, 60, false, true),
  ('Wish', 'קניות כלליות', 'https://wish.com', 'percent', 5, 60, false, true),
  ('Wondershare', 'שירותים דיגיטליים', 'https://wondershare.com', 'percent', 8, 60, false, true),
  ('Woot', 'קניות כלליות', 'https://woot.com', 'percent', 5, 60, false, true),
  ('Wrangler', 'אופנה', 'https://wrangler.com', 'percent', 6, 60, false, true),
  ('Zer4u', 'מזון ומשלוחים', 'https://zer4u.co.il', 'percent', 4, 60, false, true),
  ('Zolpo', 'קניות כלליות', 'https://zolpo.co.il', 'percent', 5, 60, false, true)
) as v(name, category, base_url, cashback_type, cashback_value, user_share_percent, variable, active)
where not exists (select 1 from public.stores s where s.name = v.name);
